### ISSUE TITLE
Push Notification Do Not Work for Below Code

### ISSUE THREAD

**Issue by tusharuit25** [angelobelchior/FCM.Net#10]
```namespace PushNotificationTest2
{
    class Program
    {
        static void Main(string[] args)
        {

            SendNotification();

        }
        private static async void SendNotification()
        {
            try
            {
                var serverKey = "XXXX";
                var senderId = "XXXXX";
                string registrationId = "XXXXX";

                using (var sender = new Sender(serverKey, senderId))
                {
                    var message = new Message
                    {
                        RegistrationIds = new List<string> { registrationId },
                        Notification = new Notification
                        {
                            Title = "Test from FCM.Net",
                            Body = $"Hello World@!{DateTime.Now.ToString()}"
                        }
                    };
                    var result = await sender.SendAsync(message);
                    Console.WriteLine($"Success: {result.MessageResponse.Success}");

                    var json = "{\"notification\":{\"title\":\"json message\",\"body\":\"works like a charm!\"},\"to\":\"" + registrationId + "\"}";
                    result = await sender.SendAsync(json);
                    Console.WriteLine($"Success: {result.MessageResponse.Success}");
                }
            }
            catch (Exception ex)
            {

                Console.Out.WriteLine(ex.Message);
            }
            
        }
    }
}
`

**Comment by tusharuit25** [comment]
'PushNotificationTest2.vshost.exe' (CLR v4.0.30319: PushNotificationTest2.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PushNotificationTest2.vshost.exe' (CLR v4.0.30319: PushNotificationTest2.vshost.exe): Loaded 'C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.HostingProcess.Utilities\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.HostingProcess.Utilities.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PushNotificationTest2.vshost.exe' (CLR v4.0.30319: PushNotificationTest2.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PushNotificationTest2.vshost.exe' (CLR v4.0.30319: PushNotificationTest2.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PushNotificationTest2.vshost.exe' (CLR v4.0.30319: PushNotificationTest2.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PushNotificationTest2.vshost.exe' (CLR v4.0.30319: PushNotificationTest2.vshost.exe): Loaded 'C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.HostingProcess.Utilities.Sync\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.HostingProcess.Utilities.Sync.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PushNotificationTest2.vshost.exe' (CLR v4.0.30319: PushNotificationTest2.vshost.exe): Loaded 'C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PushNotificationTest2.vshost.exe' (CLR v4.0.30319: PushNotificationTest2.vshost.exe): Loaded 'C:\Users\user\Documents\Visual Studio 2015\Projects\11_07\PushNotificationTest2\PushNotificationTest2\bin\Debug\PushNotificationTest2.vshost.exe'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PushNotificationTest2.vshost.exe' (CLR v4.0.30319: PushNotificationTest2.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PushNotificationTest2.vshost.exe' (CLR v4.0.30319: PushNotificationTest2.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PushNotificationTest2.vshost.exe' (CLR v4.0.30319: PushNotificationTest2.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Data.DataSetExtensions\v4.0_4.0.0.0__b77a5c561934e089\System.Data.DataSetExtensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PushNotificationTest2.vshost.exe' (CLR v4.0.30319: PushNotificationTest2.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PushNotificationTest2.vshost.exe' (CLR v4.0.30319: PushNotificationTest2.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PushNotificationTest2.vshost.exe' (CLR v4.0.30319: PushNotificationTest2.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PushNotificationTest2.vshost.exe' (CLR v4.0.30319: PushNotificationTest2.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PushNotificationTest2.vshost.exe' (CLR v4.0.30319: PushNotificationTest2.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http.WebRequest\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.WebRequest.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x9a04 has exited with code 0 (0x0).
The thread 0x9bc4 has exited with code 0 (0x0).
'PushNotificationTest2.vshost.exe' (CLR v4.0.30319: PushNotificationTest2.vshost.exe): Loaded 'C:\Users\user\Documents\Visual Studio 2015\Projects\11_07\PushNotificationTest2\PushNotificationTest2\bin\Debug\PushNotificationTest2.exe'. Symbols loaded.
'PushNotificationTest2.vshost.exe' (CLR v4.0.30319: PushNotificationTest2.vshost.exe): Loaded 'C:\Users\user\Documents\Visual Studio 2015\Projects\11_07\PushNotificationTest2\PushNotificationTest2\bin\Debug\FCM.Net.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'PushNotificationTest2.vshost.exe' (CLR v4.0.30319: PushNotificationTest2.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x9a94 has exited with code 0 (0x0).
The thread 0xa2d8 has exited with code 0 (0x0).
The program '[40568] PushNotificationTest2.vshost.exe' has exited with code 0 (0x0).

**Comment by angelobelchior** [comment]
Hy @tusharuit25 , can you send me the exception message and the stacktrace? I'm  testing the push notification and it works fine for me :/

**Comment by tusharuit25** [comment]
Above Pasted code with some of the fire base account is not working and I am not getting any exception too,instead send me example console app which you are getting success with.

**Comment by tusharuit25** [comment]
Above Pasted code with some of the fire base account is not working and I am not getting any exception too nor notification but if same account information is used with generic code which I had pasted in my last issue it works ,instead send me example console app which you are getting success with.
var result = await sender.SendAsync(message);
this line debugger gets stopped
although I have
Console.WriteLine($"Success: {result.MessageResponse.Success}");
next to execute

**Comment by Hussamalsh** [comment]
I have the same problem after the var result = await sender.SendAsync(message); nothing get excuted its going to caller method directly.
