### ISSUE TITLE
Server Key in documentation is wrong

### ISSUE THREAD

**Issue by NPadrutt** [angelobelchior/FCM.Net#11]
Hi

First: thanks for your library!

You write in your documentation:
```
var serverKey = "https://console.firebase.google.com/project/MY_PROJECT/settings/cloudmessaging";
new Sender(serverKey)
```
This gives an error. In the playground you pass there an key instead of a URL. So it seems we have to pass the ServerKey from the FCM Project.
Maybe it would make sense to update the documentation here :)

**Comment by angelobelchior** [comment]
Hi @NPadrutt !
Thank you so much! 
I just fixed the documentation

:)
