### ISSUE TITLE
Does this library helps to get ID generated when device(website)  is registered in FCM?

### ISSUE THREAD

**Issue by Divyang16** [angelobelchior/FCM.Net#12]
As defined in a sample, you can use  registered Id, but can I get registered Id using this library?
And shall I  send notification in bulk?
If it's possible with this library, then please provide some sample code.

**Comment by angelobelchior** [comment]
No, this library is designed to send push notifications using Google FCM. I recommend to read the FCM documentation: https://firebase.google.com/docs/cloud-messaging
