### ISSUE TITLE
Não chega a notificação no celular

### ISSUE THREAD

**Issue by ivanteles** [angelobelchior/FCM.Net#23]
Grande Ângelo, tenho acompanhado diversas aulas e curso que você tem postado por ai.
Agora tentando fazer o push funcionar usando FCM ja usei varias bibliotecas entre uma delas essa sua e não chega a notificação.
O que deve está errado eu meu código? o result é este:
![capturar](https://user-images.githubusercontent.com/843086/43339435-b1c5c0ce-91af-11e8-804e-9c7fa4f0d78e.JPG)

Na instancia da minha classe Sender passo certinho os dados abaixo, ja tentei tb sem o ID:
![capturar1](https://user-images.githubusercontent.com/843086/43339616-390fd678-91b0-11e8-8a31-2835f90fa9a5.JPG)

**Comment by angelobelchior** [comment]
Faltou um await:  

var result = await sender.SendAsync(message)

**Comment by ivanteles** [comment]
Mesmo com o await não chega a notificação no celular.

**Comment by ivanteles** [comment]
Então o uso do await não era..
não sei dizer o que era. mas fui no painel do firebase, deletei a chave de servidor e criei uma nova e resolveu!
