### ISSUE TITLE
How many notifications can be sent simultaneously with FCM .net

### ISSUE THREAD

**Issue by ofcerci4826** [angelobelchior/FCM.Net#27]
Hi

I want to send notifications to about  30K users, so How many users can I notify at the same time with FCM.net ?

**Comment by angelobelchior** [comment]
You will need to queue these messages and send in batch. I recommend sending every 100

**Comment by ofcerci4826** [comment]
> You will need to queue these messages and send in batch. I recommend sending every 100

Thanks for your reply angelo, 

How can i do that ? Have you got any example or tutorial?

**Comment by angelobelchior** [comment]
You need to add 100 RegistrationId inside RegistrationIds List.

**Comment by ofcerci4826** [comment]
> You need to add 100 RegistrationId inside RegistrationIds List.


ok i can do this but how can i find out which tokens failed ?

**Comment by angelobelchior** [comment]
The SendAsync returns a Result object. You can check if there is some error.

**Comment by ofcerci4826** [comment]
Thanks
