### ISSUE TITLE
Problema con mensajes en apps cerradas en ios

### ISSUE THREAD

**Issue by monchulanderas** [angelobelchior/FCM.Net#5]
Los mensajes no llegan a dispositivos ios cuando la aplicación está cerrada. Parece un problema con la prioridad: el json que se compone incluye la prioridad con valores 1 (normal) y 0 (high) en vez de las cadenas ("normal" o "high") correspondientes. Se propone como corrección incluir la línea:

`[JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]`

entre las líneas 48 y 49 del archivo FCM.Net/Code/Message.cs

Gracias. ¡estupenda librería!

**Comment by angelobelchior** [comment]
Obrigado, amigo! This fix will be available on the next release. I'm working on it right now.

**Comment by angelobelchior** [comment]
Bug Fixed.
New version: 1.0.2

**Comment by monchulanderas** [comment]
Estupendo, gracias.
