### ISSUE TITLE
Message.TimeToLive should be an int

### ISSUE THREAD

**Issue by gldraphael** [angelobelchior/FCM.Net#8]
The `TimeToLive` property is [defined](https://github.com/angelobelchior/FCM.Net/blob/df7851d8fc6ec25df87c7708420a0a0678481fc8/Code/Message.cs#L62) as a byte.

It must, however, be an int. The max value that can be represented by a byte is 255 seconds which is insufficient to hold the max `time_to_live` value which is 2,419,200 seconds (28 days). [Source](https://firebase.google.com/docs/cloud-messaging/concept-options#ttl)

**Comment by angelobelchior** [comment]
Fixed! Thank you! :)

https://www.nuget.org/packages/FCM.Net/1.0.4

**Comment by bull-xu** [comment]
@angelobelchior Could you please update the FCM.Net.Standard with this fix? The FCM.Net.Standard lib still using byte? data type.
