### ISSUE TITLE
It does not work for FCM notification with SenderId as mandatory 

### ISSUE THREAD

**Issue by tusharuit25** [angelobelchior/FCM.Net#9]
Is There any solution for this?

**Comment by tusharuit25** [comment]
string SERVER_API_KEY = "server api key";        
 var SENDER_ID = "application number";

**Comment by tusharuit25** [comment]
`public string SendNotification(string deviceId, string message)
    {
        string SERVER_API_KEY = "server api key";        
        var SENDER_ID = "application number";
        var value = message;
        WebRequest tRequest;
        tRequest = WebRequest.Create("https://android.googleapis.com/gcm/send");
        tRequest.Method = "post";
        tRequest.ContentType = " application/x-www-form-urlencoded;charset=UTF-8";
        tRequest.Headers.Add(string.Format("Authorization: key={0}", SERVER_API_KEY));

        tRequest.Headers.Add(string.Format("Sender: id={0}", SENDER_ID));

        string postData = "collapse_key=score_update&time_to_live=108&delay_while_idle=1&data.message=" + value + "&data.time=" + System.DateTime.Now.ToString() + "&registration_id=" + deviceId + "";
        Console.WriteLine(postData);
        Byte[] byteArray = Encoding.UTF8.GetBytes(postData);
        tRequest.ContentLength = byteArray.Length;

        Stream dataStream = tRequest.GetRequestStream();
        dataStream.Write(byteArray, 0, byteArray.Length);
        dataStream.Close();

        WebResponse tResponse = tRequest.GetResponse();

        dataStream = tResponse.GetResponseStream();

        StreamReader tReader = new StreamReader(dataStream);

        String sResponseFromServer = tReader.ReadToEnd();


        tReader.Close();
        dataStream.Close();
        tResponse.Close();
        return sResponseFromServer;
    }`

This functionality is not there ????

**Comment by angelobelchior** [comment]
hi mr @tusharuit25, I will fix soon!

**Comment by tusharuit25** [comment]
Awaiting for your updated as I am willing to use this library in my live project

**Comment by angelobelchior** [comment]
@tusharuit25  now you can passing the sender id into a new constructor. Please, feel free to test and open issues :) tks
